version: '2'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - crearCliente
            - consultarCliente
            - modificarCliente
            - eliminarCliente
            - crearArticulo
            - consultarArticulo
            - modificarArticulo
            - eliminarArticulo
        ports:
            - "8080:80"
        
    crearCliente:
        build: ./cliente/crear

    consultarCliente:
        build: ./cliente/consultar

    modificarCliente:
        build: ./cliente/modificar

    eliminarCliente:
        build: ./cliente/eliminar

    crearArticulo:
        build: ./inventario/crear

    consultarArticulo:
        build: ./inventario/consultar

    modificarArticulo:
        build: ./inventario/modificar

    eliminarArticulo:
        build: ./inventario/eliminar